package leetCode.Easy;

import java.util.Arrays;

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 */
public class EQ389FindTheDifference {
    public static char findTheDifference(String s, String t) {
    char[] arr_t=t.toCharArray();
    char[] arr_s=s.toCharArray();
        Arrays.sort(arr_t);
        Arrays.sort(arr_s);
        for (int i = 0; i < arr_t.length-1; i++) {
            if(arr_t[i]!=arr_s[i])
                return arr_t[i];
        }

        return arr_t[arr_t.length-1];
    }

    public static void main(String[] args) {
        String s="abcd";
        String t="abcde";
        System.out.println(findTheDifference(s,t));
    }
}
